development:
  adapter: postgresql
  database: ccia_database
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: ccia_database
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ccia_database
  pool: 5
  timeout: 5000